name: Deploy Go API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        working-directory: ./backend/Go_API
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER}}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        working-directory: ./backend/Go_API
        run: docker build -t ${{ secrets.DOCKER_USER }}/go_api_cmpinterest_app .
      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_USER }}/go_api_cmpinterest_app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull and Run Docker Image
        run: docker pull ${{ secrets.DOCKER_USER }}/go_api_cmpinterest_app:latest
      - name: Delete old container
        run: docker rm -f go_api_cmpinterest_app_container || true
      - name: Run docker container
        run: docker run -d -p 3536:3536 --name go_api_cmpinterest_app_container ${{ secrets.DOCKER_USER }}/go_api_cmpinterest_app:latest
